import type { ContactSeedData } from "../types";

export const sampleContacts: ContactSeedData[] = [
  {
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "+1-555-0123",
    note: "Interested in property investment",
    verified: false,
  },
  {
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@example.com",
    phone: "+1-555-0124",
    note: "First-time home buyer, looking for guidance",
    verified: true,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "+1-555-0125",
    note: "Commercial property investor",
    verified: false,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    phone: "+1-555-0126",
    note: "Looking to sell family home",
    verified: true,
  },
  {
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@example.com",
    phone: "+1-555-0127",
    note: "Real estate agent referral",
    verified: false,
  },
  {
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@example.com",
    phone: "+1-555-0128",
    note: "Property management services needed",
    verified: true,
  },
  {
    firstName: "Robert",
    lastName: "Taylor",
    email: "robert.taylor@example.com",
    phone: "+1-555-0129",
    note: "Investment property portfolio expansion",
    verified: false,
  },
  {
    firstName: "Jennifer",
    lastName: "Thomas",
    email: "jennifer.thomas@example.com",
    phone: "+1-555-0130",
    note: "First home buyer assistance required",
    verified: true,
  },
  {
    firstName: "William",
    lastName: "Jackson",
    email: "william.jackson@example.com",
    phone: "+1-555-0131",
    note: "Commercial lease negotiation",
    verified: false,
  },
  {
    firstName: "Amanda",
    lastName: "White",
    email: "amanda.white@example.com",
    phone: "+1-555-0132",
    note: "Property valuation for insurance",
    verified: true,
  },
  {
    firstName: "Christopher",
    lastName: "Harris",
    email: "chris.harris@example.com",
    phone: "+1-555-0133",
    note: "Looking for rental property investment",
    verified: false,
  },
  {
    firstName: "Jessica",
    lastName: "Martin",
    email: "jessica.martin@example.com",
    phone: "+1-555-0134",
    note: "First-time investor seeking guidance",
    verified: true,
  },
  {
    firstName: "Daniel",
    lastName: "Garcia",
    email: "daniel.garcia@example.com",
    phone: "+1-555-0135",
    note: "Commercial real estate development",
    verified: false,
  },
  {
    firstName: "Ashley",
    lastName: "Martinez",
    email: "ashley.martinez@example.com",
    phone: "+1-555-0136",
    note: "Property management consultation",
    verified: true,
  },
  {
    firstName: "James",
    lastName: "Robinson",
    email: "james.robinson@example.com",
    phone: "+1-555-0137",
    note: "Real estate portfolio optimization",
    verified: false,
  },
  {
    firstName: "Michelle",
    lastName: "Clark",
    email: "michelle.clark@example.com",
    phone: "+1-555-0138",
    note: "Home staging services needed",
    verified: true,
  },
  {
    firstName: "Matthew",
    lastName: "Rodriguez",
    email: "matthew.rodriguez@example.com",
    phone: "+1-555-0139",
    note: "Investment property analysis",
    verified: false,
  },
  {
    firstName: "Stephanie",
    lastName: "Lewis",
    email: "stephanie.lewis@example.com",
    phone: "+1-555-0140",
    note: "Property tax assessment appeal",
    verified: true,
  },
  {
    firstName: "Andrew",
    lastName: "Lee",
    email: "andrew.lee@example.com",
    phone: "+1-555-0141",
    note: "Commercial lease renewal",
    verified: false,
  },
  {
    firstName: "Nicole",
    lastName: "Walker",
    email: "nicole.walker@example.com",
    phone: "+1-555-0142",
    note: "Property insurance consultation",
    verified: true,
  },
  {
    firstName: "Joshua",
    lastName: "Hall",
    email: "joshua.hall@example.com",
    phone: "+1-555-0143",
    note: "Real estate market analysis",
    verified: false,
  },
  {
    firstName: "Kimberly",
    lastName: "Allen",
    email: "kimberly.allen@example.com",
    phone: "+1-555-0144",
    note: "Property investment strategy",
    verified: true,
  },
  {
    firstName: "Kevin",
    lastName: "Young",
    email: "kevin.young@example.com",
    phone: "+1-555-0145",
    note: "Commercial property acquisition",
    verified: false,
  },
  {
    firstName: "Angela",
    lastName: "King",
    email: "angela.king@example.com",
    phone: "+1-555-0146",
    note: "Property management services",
    verified: true,
  },
  {
    firstName: "Brian",
    lastName: "Wright",
    email: "brian.wright@example.com",
    phone: "+1-555-0147",
    note: "Real estate development project",
    verified: false,
  },
  {
    firstName: "Samantha",
    lastName: "Lopez",
    email: "samantha.lopez@example.com",
    phone: "+1-555-0148",
    note: "Property valuation services",
    verified: true,
  },
  {
    firstName: "Ryan",
    lastName: "Hill",
    email: "ryan.hill@example.com",
    phone: "+1-555-0149",
    note: "Investment property financing",
    verified: false,
  },
  {
    firstName: "Brittany",
    lastName: "Scott",
    email: "brittany.scott@example.com",
    phone: "+1-555-0150",
    note: "Property tax planning",
    verified: true,
  },
  {
    firstName: "Tyler",
    lastName: "Green",
    email: "tyler.green@example.com",
    phone: "+1-555-0151",
    note: "Real estate market research",
    verified: false,
  },
  {
    firstName: "Rachel",
    lastName: "Adams",
    email: "rachel.adams@example.com",
    phone: "+1-555-0152",
    note: "Property investment consultation",
    verified: true,
  },
  {
    firstName: "Brandon",
    lastName: "Baker",
    email: "brandon.baker@example.com",
    phone: "+1-555-0153",
    note: "Commercial real estate investment",
    verified: false,
  },
  {
    firstName: "Lauren",
    lastName: "Gonzalez",
    email: "lauren.gonzalez@example.com",
    phone: "+1-555-0154",
    note: "Property management optimization",
    verified: true,
  },
  {
    firstName: "Justin",
    lastName: "Nelson",
    email: "justin.nelson@example.com",
    phone: "+1-555-0155",
    note: "Real estate portfolio review",
    verified: false,
  },
  {
    firstName: "Megan",
    lastName: "Carter",
    email: "megan.carter@example.com",
    phone: "+1-555-0156",
    note: "Property investment education",
    verified: true,
  },
  {
    firstName: "Nathan",
    lastName: "Mitchell",
    email: "nathan.mitchell@example.com",
    phone: "+1-555-0157",
    note: "Commercial property development",
    verified: false,
  },
  {
    firstName: "Kayla",
    lastName: "Perez",
    email: "kayla.perez@example.com",
    phone: "+1-555-0158",
    note: "Property tax optimization",
    verified: true,
  },
  {
    firstName: "Zachary",
    lastName: "Roberts",
    email: "zachary.roberts@example.com",
    phone: "+1-555-0159",
    note: "Real estate investment strategy",
    verified: false,
  },
  {
    firstName: "Amber",
    lastName: "Turner",
    email: "amber.turner@example.com",
    phone: "+1-555-0160",
    note: "Property management consultation",
    verified: true,
  },
  {
    firstName: "Jacob",
    lastName: "Phillips",
    email: "jacob.phillips@example.com",
    phone: "+1-555-0161",
    note: "Commercial lease negotiation",
    verified: false,
  },
  {
    firstName: "Danielle",
    lastName: "Campbell",
    email: "danielle.campbell@example.com",
    phone: "+1-555-0162",
    note: "Property investment analysis",
    verified: true,
  },
  {
    firstName: "Austin",
    lastName: "Parker",
    email: "austin.parker@example.com",
    phone: "+1-555-0163",
    note: "Real estate development planning",
    verified: false,
  },
  {
    firstName: "Courtney",
    lastName: "Evans",
    email: "courtney.evans@example.com",
    phone: "+1-555-0164",
    note: "Property valuation services",
    verified: true,
  },
  {
    firstName: "Ethan",
    lastName: "Edwards",
    email: "ethan.edwards@example.com",
    phone: "+1-555-0165",
    note: "Investment property acquisition",
    verified: false,
  },
  {
    firstName: "Taylor",
    lastName: "Collins",
    email: "taylor.collins@example.com",
    phone: "+1-555-0166",
    note: "Property management services",
    verified: true,
  },
  {
    firstName: "Noah",
    lastName: "Stewart",
    email: "noah.stewart@example.com",
    phone: "+1-555-0167",
    note: "Commercial real estate investment",
    verified: false,
  },
  {
    firstName: "Paige",
    lastName: "Sanchez",
    email: "paige.sanchez@example.com",
    phone: "+1-555-0168",
    note: "Property tax planning",
    verified: true,
  },
  {
    firstName: "Caleb",
    lastName: "Morris",
    email: "caleb.morris@example.com",
    phone: "+1-555-0169",
    note: "Real estate market analysis",
    verified: false,
  },
  {
    firstName: "Alexis",
    lastName: "Rogers",
    email: "alexis.rogers@example.com",
    phone: "+1-555-0170",
    note: "Property investment guidance",
    verified: true,
  },
  {
    firstName: "Logan",
    lastName: "Reed",
    email: "logan.reed@example.com",
    phone: "+1-555-0171",
    note: "Commercial property development",
    verified: false,
  },
  {
    firstName: "Madison",
    lastName: "Cook",
    email: "madison.cook@example.com",
    phone: "+1-555-0172",
    note: "Property management optimization",
    verified: true,
  },
];
